///////////////////////////////////////////////////////////////////////////////////
// File : pd_defs.h
// Contains: Power delivery messages strings definitions
//
// Written by: Jean-François DEL NERO
///////////////////////////////////////////////////////////////////////////////////

enum
{
	CTRL_MSG_ID_RSVD_00 = 0,
	CTRL_MSG_ID_GOODCRC,
	CTRL_MSG_ID_GOTOMIN,
	CTRL_MSG_ID_ACCEPT,
	CTRL_MSG_ID_REJECT,
	CTRL_MSG_ID_PING,
	CTRL_MSG_ID_PS_RDY,
	CTRL_MSG_ID_Get_Source_Cap,
	CTRL_MSG_ID_Get_Sink_Cap,
	CTRL_MSG_ID_DR_Swap,
	CTRL_MSG_ID_PR_Swap,
	CTRL_MSG_ID_VCONN_Swap,
	CTRL_MSG_ID_Wait,
	CTRL_MSG_ID_Soft_Reset,
	CTRL_MSG_ID_RSVD_14,
	CTRL_MSG_ID_RSVD_15,
	CTRL_MSG_ID_Not_Supported,
	CTRL_MSG_ID_Get_Source_Cap_Extended,
	CTRL_MSG_ID_Get_Status,
	CTRL_MSG_ID_FR_Swap,
	CTRL_MSG_ID_Get_PPS_Status,
	CTRL_MSG_ID_Get_Country_Codes,
	CTRL_MSG_ID_Get_Sink_Cap_Extented,
	CTRL_MSG_ID_Get_Source_Info,
	CTRL_MSG_ID_Get_Revision,
	CTRL_MSG_ID_RSVD_25,
	CTRL_MSG_ID_RSVD_26,
	CTRL_MSG_ID_RSVD_27,
	CTRL_MSG_ID_RSVD_28,
	CTRL_MSG_ID_RSVD_29,
	CTRL_MSG_ID_RSVD_30,
	CTRL_MSG_ID_RSVD_31
};


extern const char * pd_ctrl_msg[];

enum
{
	DATA_MSG_ID_RSVD_00 = 0x100,
	DATA_MSG_ID_SOURCE_CAPABILITIES,
	DATA_MSG_ID_REQUEST,
	DATA_MSG_ID_BIST,
	DATA_MSG_ID_SINK_CAPABILITIES,
	DATA_MSG_ID_BATTERY_STATUS,
	DATA_MSG_ID_ALERT,
	DATA_MSG_ID_GET_COUNTRY_INFO,
	DATA_MSG_ID_ENTER_USB,
	DATA_MSG_ID_EPR_REQUEST,
	DATA_MSG_ID_EPR_MODE,
	DATA_MSG_ID_SOURCE_INFO,
	DATA_MSG_ID_REVISION,
	DATA_MSG_ID_RSVD_13,
	DATA_MSG_ID_RSVD_14,
	DATA_MSG_ID_VENDOR_DEFINED,
	DATA_MSG_ID_RSVD_16,
	DATA_MSG_ID_RSVD_17,
	DATA_MSG_ID_RSVD_18,
	DATA_MSG_ID_RSVD_19,
	DATA_MSG_ID_RSVD_20,
	DATA_MSG_ID_RSVD_21,
	DATA_MSG_ID_RSVD_22,
	DATA_MSG_ID_RSVD_23,
	DATA_MSG_ID_RSVD_24,
	DATA_MSG_ID_RSVD_25,
	DATA_MSG_ID_RSVD_26,
	DATA_MSG_ID_RSVD_27,
	DATA_MSG_ID_RSVD_28,
	DATA_MSG_ID_RSVD_29,
	DATA_MSG_ID_RSVD_30,
	DATA_MSG_ID_RSVD_31
};

extern const char * pd_data_msg[];

enum
{
	EXTENDED_MSG_ID_RSVD_00 = 0x200,
	EXTENDED_MSG_ID_SOURCE_CAPABILITIES,
	EXTENDED_MSG_ID_STATUS,
	EXTENDED_MSG_ID_GET_BATTERY_CAP,
	EXTENDED_MSG_ID_GET_BATTERY_STATUS,
	EXTENDED_MSG_ID_BATTERY_CAPABILITIES,
	EXTENDED_MSG_ID_GET_MANUFACTURER_INFO,
	EXTENDED_MSG_ID_MANUFACTURER_INFO,
	EXTENDED_MSG_ID_SECURITY_REQUEST,
	EXTENDED_MSG_ID_SECURITY_RESPONSE,
	EXTENDED_MSG_ID_FIRMWARE_UPDATE_REQUEST,
	EXTENDED_MSG_ID_FIRMWARE_UPDATE_RESPONSE,
	EXTENDED_MSG_ID_PPS_STATUS,
	EXTENDED_MSG_ID_COUNTRY_INFO,
	EXTENDED_MSG_ID_COUNTRY_CODES,
	EXTENDED_MSG_ID_RSVD_15,
	EXTENDED_MSG_ID_RSVD_16,
	EXTENDED_MSG_ID_RSVD_17,
	EXTENDED_MSG_ID_RSVD_18,
	EXTENDED_MSG_ID_RSVD_19,
	EXTENDED_MSG_ID_RSVD_20,
	EXTENDED_MSG_ID_RSVD_21,
	EXTENDED_MSG_ID_RSVD_22,
	EXTENDED_MSG_ID_RSVD_23,
	EXTENDED_MSG_ID_RSVD_24,
	EXTENDED_MSG_ID_RSVD_25,
	EXTENDED_MSG_ID_RSVD_26,
	EXTENDED_MSG_ID_RSVD_27,
	EXTENDED_MSG_ID_RSVD_28,
	EXTENDED_MSG_ID_RSVD_29,
	EXTENDED_MSG_ID_RSVD_30,
	EXTENDED_MSG_ID_RSVD_31
};

extern const char * pd_extended_msg[];

// --------------------------------------
// SOP
// --------------------------------------

// SOP   : CODE_SYNC_1->CODE_SYNC_1->CODE_SYNC_1->CODE_SYNC_2 : Communication to UFP
// SOP'  : CODE_SYNC_1->CODE_SYNC_1->CODE_SYNC_3->CODE_SYNC_3 : Communication to USB Type-C Plug Side A
// SOP'' : CODE_SYNC_1->CODE_SYNC_3->CODE_SYNC_1->CODE_SYNC_3 : Communication to USB Type-C Plug Side B

// Hard Reset  : CODE_RST_1  CODE_RST_1  CODE_RST_1  CODE_RST_2   : Resets logic in all connected PD devices (UFP and/or Active/Electronically Marked Cable)
// Cable Reset : CODE_RST_1  CODE_SYNC_1 CODE_RST_1  CODE_SYNC_3  : Reset for only Active/Electronically Marked Cable.
// SOP’_Debug  : CODE_SYNC_1 CODE_RST_2  CODE_RST_2  CODE_SYNC_3  : Used for debug of USB Type-C Plug Side A
// SOP’’_Debug : CODE_SYNC_1 CODE_RST_2  CODE_SYNC_3 CODE_SYNC_2  : Used for debug of USB Type-C Plug Side B

#define SOP        ( (CODE_SYNC_1<<(3*8)) | (CODE_SYNC_1<<(2*8)) | (CODE_SYNC_1<<(1*8)) | (CODE_SYNC_2<<(0*8)) )
#define SOP1       ( (CODE_SYNC_1<<(3*8)) | (CODE_SYNC_1<<(2*8)) | (CODE_SYNC_3<<(1*8)) | (CODE_SYNC_3<<(0*8)) )
#define SOP2       ( (CODE_SYNC_1<<(3*8)) | (CODE_SYNC_3<<(2*8)) | (CODE_SYNC_1<<(1*8)) | (CODE_SYNC_3<<(0*8)) )
#define HARDRESET  ( (CODE_RST_1 <<(3*8)) | (CODE_RST_1 <<(2*8)) | (CODE_RST_1 <<(1*8)) | (CODE_RST_2 <<(0*8)) )
#define CABLERESET ( (CODE_RST_1 <<(3*8)) | (CODE_SYNC_1<<(2*8)) | (CODE_RST_1 <<(1*8)) | (CODE_SYNC_3<<(0*8)) )

#define SOP1DEBUG  ( (CODE_SYNC_1 <<(3*8)) | (CODE_RST_2<<(2*8)) | (CODE_RST_2 <<(1*8)) | (CODE_SYNC_3<<(0*8)) )
#define SOP2DEBUG  ( (CODE_SYNC_1 <<(3*8)) | (CODE_RST_2<<(2*8)) | (CODE_SYNC_3<<(1*8)) | (CODE_SYNC_2<<(0*8)) )
